#!/usr/bin/env python3
"""Regenerate FAQ artifacts from reference/TAC_Master_FAQ_Repository.xlsx.

Reads the 'FAQs with Draft Answers' tab (the authoritative answered set) and
writes:
  - scripts/data/faq-master.json  (consumed by scripts/seed-faq-items.mjs)
  - agent/faq-kb.md               (the manual:faq-master-repository KB doc)

Run after every xlsx update, then:
  node scripts/seed-faq-items.mjs <env>   # site FAQ page
  (re-upload agent/faq-kb.md to the ElevenLabs agents + rag-index)
"""
import json
import re
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
SHEET = 'FAQs with Draft Answers'

# Department Owner → site FAQ category (enum) and citation page.
DEPT = {
    'membership':            ('membership', 'Membership', 'https://amclub.org.sg/membership'),
    'membership/front desk': ('membership', 'Membership', 'https://amclub.org.sg/membership'),
    'f&b':                   ('dining', 'Dining', 'https://amclub.org.sg/dining'),
    'f&l':                   ('facilities', 'Fitness', 'https://amclub.org.sg/fitness'),
    'tennis':                ('facilities', 'Tennis', 'https://amclub.org.sg/fitness/tennis'),
    'aquatics':              ('facilities', 'Aquatics', 'https://amclub.org.sg/fitness/aquatics'),
    'spa':                   ('facilities', 'sên Spa', 'https://amclub.org.sg/fitness/sen-spa'),
    'thinkspace':            ('facilities', 'Event Spaces', 'https://amclub.org.sg/event-spaces'),
    'y&f':                   ('kids', 'Kids', 'https://amclub.org.sg/kids'),
    'events':                ('events', "What's On", 'https://amclub.org.sg/whats-on'),
    'member engagement':     ('events', "What's On", 'https://amclub.org.sg/whats-on'),
    'general':               ('general', 'FAQ', 'https://amclub.org.sg/faq'),
    '':                      ('general', 'FAQ', 'https://amclub.org.sg/faq'),
}


def slugify(q: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', q.lower()).strip('-')[:80].rstrip('-')


def main() -> None:
    wb = openpyxl.load_workbook(ROOT / 'reference/TAC_Master_FAQ_Repository.xlsx', data_only=True)
    ws = wb[SHEET]
    items, seen = [], set()
    for r in ws.iter_rows(min_row=2, values_only=True):
        _, q, dept, ans = (tuple(r) + (None,) * 4)[:4]
        if not q or not str(q).strip() or not ans or not str(ans).strip():
            continue
        q, ans = str(q).strip(), str(ans).strip()
        dept_key = str(dept or '').strip().lower()
        if dept_key not in DEPT:
            raise SystemExit(f'unmapped Department Owner: {dept!r} — add it to DEPT')
        cat, _, _ = DEPT[dept_key]
        slug = slugify(q)
        while slug in seen:
            slug += '-2'
        seen.add(slug)
        items.append({
            'question': q,
            'slug': slug,
            'answer': ans,
            'category': cat,
            'department': str(dept or '').strip(),
            'order': len(items) + 1,
        })

    (ROOT / 'scripts/data/faq-master.json').write_text(
        json.dumps(items, indent=1, ensure_ascii=False))

    # KB doc: grouped by department, per-QA titled Source line so every RAG
    # chunk carries a citable page.
    lines = [
        '<!-- GENERATED by scripts/generate-faq-master.py from',
        "     reference/TAC_Master_FAQ_Repository.xlsx (sheet 'FAQs with Draft Answers').",
        '     This is the "manual:faq-master-repository" knowledge-base document uploaded to the',
        '     ElevenLabs agents (dev on the agency account; uat + prod on the Club account).',
        '     Regenerate + re-upload when the FAQ changes. -->',
        '',
        '# The American Club Singapore — Master FAQ Repository',
        '',
        '> Source: [FAQ](https://amclub.org.sg/faq)',
        '',
        'Frequently asked questions and answers, organized by department. Each answer lists the page with more details.',
        '',
    ]
    last_dept = None
    for it in items:
        dept_label = it['department'] or 'General'
        if dept_label != last_dept:
            lines += [f'## {dept_label}', '']
            last_dept = dept_label
        _, src_title, src_url = DEPT[it['department'].lower() if it['department'] else '']
        lines += [f"### {it['question']}", it['answer'], f'Source: [{src_title}]({src_url})', '']
    (ROOT / 'agent/faq-kb.md').write_text('\n'.join(lines))
    print(f'wrote {len(items)} items -> faq-master.json + faq-kb.md')


if __name__ == '__main__':
    main()
